ReactDOM.render(<div>
    <h1 id="hii">BIOGRAPHY</h1>
    <center> <img src="https://ik.imagekit.io/j83rchiauw/A_List_Star/ramcharan-webbanner.tring.png" ></img></center>
    <p class="para">Ram Charan's full name is Ram Charan Teja, an Indian actor, producer, and businessman who primarily works in Telugu films. Ram Charan is one of the highest-paid Telugu film actors and has won two Nandi Awards and three Filmfare Awards. He has appeared in Forbes India's Celebrity 100 list since 2013. 
    With the box office success of Chirutha (2007), Charan made his acting debut and took home the Filmfare Best Male Debut Award. The fantasy action movie Magadheera (2009), directed by S. S. Rajamouli, catapulted him to fame and earned him the Filmfare Best Actor Award at the time. Racha (2012), Naayak (2013), Yevadu (2014), Govindudu Andarivadele (2014), and Dhruva are some of his well-known works (2016). After that, Charan appeared in the box office successes Rangasthalam (2018), for which he received his second Filmfare Best Actor Award, and RRR (2022), which brought in more than 1150 crore globally.
    In 2016, Charan established his own production company, Konidela Production Company, which has notably supported Sye Raa Narasimha Reddy and Khaidi No. 150 (2017). (2019). In addition to his work in movies, he co-owns the regional airline service TruJet and the polo team Hyderabad Polo and Riding Club.</p>
   <center> 
    <h1>Childhood</h1>
     <img src="https://ik.imagekit.io/j83rchiauw/A_List_Star/ramcharan-childhoodlifeandeducation.tring.png"></img>
    </center>  
    <p>Ram Charan was born on March 27, in the year 1985,  Ram Charan's father is Telugu actor Chiranjeevi and Ram Charan's mother is Surekha gave birth to Ram Charan in Madras (now Chennai). His sister's number two. He is the nephew of Nagendra Babu, Pawan Kalyan, and Allu Aravind and the grandson of Allu Ramalingaiah. He is the cousin of Niharika Konidela, Panja Vaissnav Tej, Sai Dharam Tej, Allu Sirish, Varun Tej, and Allu Arjun.</p>
        <center><h1>Education</h1></center>
        <p>Ram Charan's education was completed at a number of institutions, including Ram Charan's college St. Mary's College in Hyderabad, Padma Seshadri Bala Bhavan in Chennai, and Ram Charan's school Lawrence School in Lovedale, and The Hyderabad Public School in Begumpet. Ram Charan was motivated to pursue an acting career and studied at Kishore Namit Kapoor's acting studio in Mumbai, Maharashtra, to hone his craft.</p>
        <center><h1>Family</h1>
        <img src="https://ik.imagekit.io/j83rchiauw/A_List_Star/ramcharan-family.tring.png"></img>
        </center>
        <p>Konidela The megastar Chiranjeevi and Surekha's son, Ram Charan Teja, was born. Sushmita and Srija, his older sisters, are his siblings. His cousin is the well-known Tollywood star Allu Arjun. Despite being well-known as Chirenjeevi's son, Ram Charan is also the great-grandson of Allu Rama Lingaiah, a doctor who participated actively in India's freedom war. He performed in over a thousand Telugu movies and was also a well-known comedian. His paternal uncles are the actor Pawan Kalyan and the director Nagendra Babu, while his maternal uncle is the director Allu Aravind. He obviously has a lot of cinematic experience. </p>
        <center><h1>Best Movies</h1>
                <h2>RRR</h2>
                <img src="https://th.bing.com/th/id/OIP.4chr6pDkoJhJQ7JeBzUeTwHaEe?w=292&h=180&c=7&r=0&o=5&pid=1.7"></img>
                </center>
        <p>The epic action drama RRR was written by V. Vijayendra Prasad and S. S. Rajamouli, and it was directed by S. S. Rajamouli in 2022. D. V. V. Danayya of DVV Entertainment produced it. N. T. Rama Rao Jr., Ram Charan, Alia Bhatt, Shriya Saran, Samuthirakani, Ray Stevenson, Alison Doody, and Olivia Morris are among the actors who appear in the movie. Two real-life Indian revolutionaries, Alluri Sitarama Raju (Charan) and Komaram Bheem (Rama Rao), and their struggle against the British Raj are the subject of this fictitious tale. The story, which is set in 1920, focuses on the unrecorded time of their life when both revolutionaries choose to live in obscurity before waging war for their nation. 
        Rajamouli read accounts of Rama Raju and Bheem's lives and drew connections between them, speculating on what may have happened if they had crossed paths and became friends. The movie had a formal announcement in March 2018. Due to delays brought on by the COVID-19 pandemic, principal photography for the movie didn't finish until August 2021. It started in Hyderabad in November 2018. With a few scenes in Ukraine and Bulgaria, the movie was primarily shot in India. M. M. Keeravani composed the soundtrack and background music for the movie, which was shot by K. K. Senthil Kumar and edited by A. Sreekar Prasad. The production designer for the movie is Sabu Cyril, and V. Srinivas Mohan oversaw the visual effects.</p>
       <center>
        <h2>Rangsthalam</h2>
        <img src="https://ik.imagekit.io/j83rchiauw/A_List_Star/ramcharan-rangsthalam.tring.png"></img>
        </center>
        <p>
        Sukumar wrote and directed the 2018 Telugu-language period action drama movie Rangasthalam. The movie, which is directed by Ram Charan and Samantha Akkineni and produced by Y. Naveen, Y. Ravi Shankar, and C. V. Mohan for the business Mythri Movie Makers, also has Aadhi Pinisetty, Jagapathi Babu, Prakash Raj, Naresh, and Anasuya Bharadwaj in pivotal supporting parts. The 1980s are the backdrop for the imaginary village of Rangasthalam. It tells the tale of two brothers, Chittibabu (Charan) and Kumar Babu (Pinisetty), who rebel against the corrupt co-operative society headed by its president Phanindra Bhupathi and the local government of their town (Babu). 
        After finishing Nannaku Prematho (2016), Sukumar began writing the script for the movie with R. Rathnavelu, who was also the director of photography. The soundtrack and score for the movie were written by Devi Sri Prasad, and Naveen Nooli edited it. Rangasthalam, which had the working title RC11 when it started principal photography in April 2017, was one of the first few Indian movies to be exclusively shot on Red Helium 8K cameras. Principal photography ended in March 2018. 10% of the movie's material was filmed in and around Rajahmundry, but the most of the movie was filmed on a village set that cost 5 crore to build in Hyderabad.
        </p>
        <center><h2>Magadheera</h2><img src="https://th.bing.com/th/id/OIP.Nx1vsxedAqH0x4UA2t0-YAHaFj?w=228&h=180&c=7&r=0&o=5&pid=1.7"></img>
        </center>
        <p>The 2009 fantasy action movie Magadheera was written and co-directed by S. S. Rajamouli and V. Vijayendra Prasad. Geetha Arts' Allu Aravind produced it. Ram Charan, Srihari, Kajal Aggarwal, and Dev Gill are the movie's main actors. The heroic warrior in charge of a princess' safety, the princess who is in love with him, the army commander-in-chief who has a thing for the princess, and an emperor who wants to take over their realm are the four main characters in the reincarnation-themed story. The plot then shifts 400 years into the future, where the reincarnated warrior begins experiencing memories after a chance meeting with the reincarnated princess. They all pass away before their wishes are granted.
        It was the most costly Telugu movie at the time, with a budget of 35-44 crore (about $7–10 million). Production on the movie started on March 2, 2008, and on March 19, 2008, principal photography started. Kotagiri Venkateswara Rao edited the film, which was edited by K. K. Senthil Kumar. R. Ravinder handled the production design, and Peter Hein and the Ram-Lakshman team choreographed the action scenes. R. C. Kamalakannan created the visual effects with help from Pete Draper and Adel Adili. It was the first Telugu movie whose credits included the phrase "visual effects producer." M. M. Keeravani, who worked with Kalyani Malik to score the background music, created the soundtrack.</p>
        <center><h2>Dhruva</h2><img src="https://ik.imagekit.io/j83rchiauw/A_List_Star/ramcharan-dhruva.tring.png"></img></center>
       <p>Surender Reddy directed the 2016 action-thriller movie Dhruva, which was also produced by Allu Aravind through his Geetha Arts production company. As addition to Aravind Swamy, Rakul Preet Singh, and Navdeep playing significant roles, it stars Ram Charan in the lead role. The film Thani Oruvan (2015), directed by Mohan Raja, is an official remake of the Tamil original. It centers on Dhruva, an IPS officer who seeks to apprehend Siddharth Abhimanyu, a rich scientist who makes money using illegal and covert medical procedures.
       The movie was released and started primary photography in February 2016 it was filmed in Kashmir and Hyderabad. Hiphop Tamizha composed the music for the movie, P. S. Vinod handled the cinematography, and Navin Nooli handled the editing. After several delays, the movie finally had its global premiere on December 9, 2016, to generally positive reviews that praised the writing, direction, action scenes, and cinematography of the movie as well as the performances of the cast, especially Ram Charan and Arvind Swamy.</p>
      <center><h1>Upcoming Movies</h1></center>
      <p>Gowtam Tinnanuri, known for his work on the Jersey film series, is the director of the love comedy RC 16. Ram Charan plays the lead in the film. Under the NVR Cinema and UV Creations labels, NV Prasad and UV Creations co-produced the movie. Dharani is the director of the action film Merupu in Telugu. Ram Charan Teja and Kajal Aggarwal are among the Merupu cast members.
       The India House Ram Charan has announced that he'll be producing the new movie The India House starring Nikhil Siddhartha and anupam kher.</p>
      <center><h1>Net Worth</h1><img src="https://ik.imagekit.io/j83rchiauw/A_List_Star/ramcharan-networth.tring.png"></img></center>
      <p>According to estimates, Ram Charan's Net worth 175 million dollars. The estimated value of Ram Charan's net worth in Indian rupees is 1370.00 billion rupees, or approximately 1,370,000,000,000 INR. His film work and brand endorsements account for the majority of his earnings. Along with his playing compensation, Ram Charan also receives a portion of the movie's profits. He accepts a sizable payment for brand endorsement. Ram Charan resides in Jubilee Hills, a prestigious neighbourhood in Hyderabad. This real estate property is worth an estimated 38 crore Indian rupees. He is the owner of numerous real estate assets across the nation.
       Ram Charan has a sizable collection of automobiles. He is the owner of several of the world's top premium vehicles. Ram Charan is the owner of the car companies Aston Martin and Range Rover. These cars would each cost between 1 and 3 crores. </p>
     <center><h1>Awards</h1><img src="https://ik.imagekit.io/j83rchiauw/A_List_Star/ramcharan-awards.tring.png"></img>
    <br/><br/> Ram Charan has won Nandi Awards for the film Chirutha.<br/>
    <br/> Ram Charan has won Nandi Awards for the film Magadheera.<br/>
    <br/> Ram Charan has won Filmfare Award South for the film Magadheera. <br/>
    <br/> Ram Charan has won South Indian International Movie Award for Best Actor for the film Magadheera.<br/>
    </center>
    </div>,document.getElementById('main'));